before_script:
- docker info

build-job:
  stage: build
  tags:
    - Docker
  script:
    - echo "Injecting Docker Credentials to .env..."
    - echo $'\nDISCORD_TOKEN='$DISCORD_TOKEN >> bot/.env
    - echo $'\nDISCORD_GUILD='$DISCORD_GUILD >> bot/.env
    - echo "Building Docker Image..."
    - docker build --tag "gitlab.ho-me.zone/conamu/eberhard-pauker/eberhard-pauker:latest" .

deploy-prod:
  stage: deploy
  tags:
    - Docker
  script:
    - echo "Logging in to Docker registry..."
    - docker login -p $DOCKER_PW -u $DOCKER_UN  $REGISTRY 
    - echo "Pushing Image to Registry!"
    - docker push conamu470/eberhard-pauker
