image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker info

build-job:
  stage: build
  script:
    - echo "Building Docker Image"
    - docker build --tag "conamu470/eberhard-pauker" .

deploy-prod:
  stage: deploy
  script:
    - echo "Logging in to Dockerhub..."
    - docker login -p v5i7aLP6spvvbzc2 -u conamu470
    - echo "Pushing Image to Dockerhub!"
    - docker push build --tag "conamu470/eberhard-pauker"
